// Client report data (generated by the IL-meta-leads pipeline). Client-safe fields only.
// One entry per client, keyed by an unguessable slug. Page: /p/<slug>
export const REPORTS = {
 "stav-56f5e275": {
  "slug": "stav-56f5e275",
  "business": {
   "name": "סתיו תכשיטי יוקרה",
   "owner_first": "סתיו",
   "site": "https://stav-fine-jewelry.com/",
   "wordmark": "סתיו",
   "signature": "סתיו"
  },
  "insights": [
   {
    "t": "הסרטונים שלך עובדים",
    "d": "שני הסרטונים שבהם את מדברת מול המצלמה רצים כבר יותר משנה וחצי. זה סימן חזק שהקהל מתחבר אלייך ולסיפור שלך."
   },
   {
    "t": "התמונות הסטטיות לא מספרות את זה",
    "d": "המודעות הסטטיות הן תמונות קטלוג על רקע לבן. התכשיטים ברמה של קמפיין מגזין, והוויזואל עדיין לא משדר את זה."
   },
   {
    "t": "יהלומי המעבדה מחכים לבמה",
    "d": "טבעת 1.50 קראט ב־5,300 ש״ח היא יתרון עצום, והיא עדיין לא עומדת במרכז אף מודעה."
   },
   {
    "t": "ההטבות לא מופיעות",
    "d": "5% על שלושה תכשיטים ומשלוח חינם מעל 1,000 ש״ח נמצאים באתר, ולא במודעות."
   }
  ],
  "angles": [
   {
    "id": "A1",
    "name": "המעצבת מאחורי התכשיט",
    "hook": "כל תכשיט כאן מתחיל בסקיצה שלי.",
    "idea": "הסרטונים שבהם את מדברת מול המצלמה הם המודעות הכי ותיקות שלך. לקחנו את הכוח הזה גם לתמונות: הידיים, הסקיצה, הבוטיק, והמשפטים שלך ככותרת."
   },
   {
    "id": "A2",
    "name": "יהלום מעבדה, בלי פשרה",
    "hook": "אותו יהלום. אותו ברק. בלי המכרה.",
    "idea": "יהלום מעבדה הוא היתרון הכי חזק שלך מבחינת מחיר מול ברק. המודעות האלה מסבירות אותו בקצרה, בביטחון, ומעמידות את הטבעות במרכז."
   },
   {
    "id": "A3",
    "name": "המתנה שהיא לא תשכח",
    "hook": "היא תזכור מי נתן לה את זה.",
    "idea": "מודעות למי שקונה מתנה: בני זוג, ימי נישואין, ימי הולדת. קהל עם כוונת קנייה גבוהה, שהיום לא מקבל מודעה משלו."
   },
   {
    "id": "A4",
    "name": "טבע בזהב",
    "hook": "פרחים נובלים. זהב נשאר.",
    "idea": "תקריבים על קולקציית הפרחים: זהב 14K, אמרלד טבעי, עבודת יד. הפרטים הקטנים שתמונת קטלוג לא מראה."
   },
   {
    "id": "A5",
    "name": "עיצוב אישי",
    "hook": "אותו עיצוב. האבן שלך.",
    "idea": "ההתאמה האישית היא משהו שרשתות לא יכולות להציע. המודעות האלה שמות אותה במרכז: אבן, גוון זהב ומידה, לפי הטעם שלה."
   }
  ],
  "ads": [
   {
    "no": 1,
    "angle": "A1",
    "format": "4:5",
    "img": "/reports/stav/raw_01.webp",
    "headline": "עבודת יד מהסטודיו בשינקין",
    "primary": "התכשיט הזה לא יצא מפס ייצור.\n\nהוא התחיל כסקיצה על השולחן שלי, נוצק בזהב 14K ושובץ ביד, אבן אחרי אבן.\n\nככה נוצר כל תכשיט אצלי, בסטודיו בשינקין 48.\n\nרוצה לראות את הקולקציה מקרוב? מחכה לך באתר או בבוטיק.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "contrast",
     "box": [
      64,
      67,
      496,
      364
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(1,1,1)",
     "scrim": "rgba(0,0,0,0.14)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "לא מפעל.<br>סטודיו בשינקין.",
     "sub": "עבודת יד · זהב 14K",
     "note": "כל תכשיט מתחיל אצלי בסקיצה.",
     "signature": "סתיו"
    }
   },
   {
    "no": 2,
    "angle": "A1",
    "format": "1:1",
    "img": "/reports/stav/raw_02.webp",
    "headline": "מהסקיצה ועד התכשיט",
    "primary": "כל תכשיט שלי מתחיל בעיפרון.\n\nהפרח הזה נולד כסקיצה קטנה על נייר, ובסוף הפך לזהב 14K עם אמרלד טבעי בלב.\n\nאין פה תבנית מקטלוג. יש מעצבת שיושבת על כל פרט.\n\nהקולקציה המלאה באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1080,
     "direction": "stack",
     "box": [
      86,
      54,
      993,
      334
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(237,234,231)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "מהסקיצה שלי,<br>לצוואר שלך.",
     "sub": "סתיו דוידוביץ' · מעצבת תכשיטים",
     "note": "כל תכשיט מתחיל אצלי בסקיצה.",
     "signature": "סתיו"
    }
   },
   {
    "no": 3,
    "angle": "A1",
    "format": "9:16",
    "img": "/reports/stav/raw_03.webp",
    "headline": "טבעות בעבודת יד, זהב 14K",
    "primary": "יש הבדל בין תכשיט שקונים לתכשיט שמישהי יצרה.\n\nאני מעצבת כל דגם בעצמי, יוצקת אותו בזהב ומשבצת את האבנים ביד.\n\nזה לוקח יותר זמן. וזה מרגישים ברגע שהוא על היד.\n\nהטבעות החדשות מחכות באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1920,
     "direction": "stack",
     "box": [
      86,
      250,
      993,
      749
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(6,4,4)",
     "scrim": "rgba(0,0,0,0.14)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "כל תכשיט<br>עובר בידיים שלי.",
     "sub": "סקיצה · יציקה · שיבוץ",
     "note": "כל תכשיט מתחיל אצלי בסקיצה.",
     "signature": "סתיו"
    }
   },
   {
    "no": 4,
    "angle": "A1",
    "format": "4:5",
    "img": "/reports/stav/raw_04.webp",
    "headline": "הזיכרון הבא שלך מתחיל כאן",
    "primary": "אולי קיבלת אותו אחרי התואר. אולי ממישהו שאת אוהבת. אולי מסבתא.\n\nתכשיט נשאר איתך כל יום, על היד ועל הצוואר, ובכל פעם שאת נוגעת בו את נזכרת.\n\nבשביל זה אני מעצבת תכשיטים שנשארים: זהב 14K, אבני חן טבעיות, עבודת יד.\n\nבואי ליצור את הזיכרון הבא שלך.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "note",
     "box": [
      86,
      67,
      993,
      418
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(242,238,232)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate_bg": null,
     "brand_color": "#231a12",
     "obj_pos": "center",
     "plate": false,
     "headline": "תכשיט הוא זיכרון<br>שנושאים כל יום.",
     "sub": "",
     "note": "כל תכשיט מתחיל אצלי בסקיצה.",
     "signature": "סתיו"
    }
   },
   {
    "no": 5,
    "angle": "A2",
    "format": "4:5",
    "img": "/reports/stav/raw_05.webp",
    "headline": "סוליטר 1.50 קראט ב־₪5,300",
    "primary": "יהלום מעבדה הוא יהלום. לא חיקוי ולא זירקון.\n\nאותו פחמן, אותה קשיות, אותו ברק. ההבדל היחיד הוא שהוא גדל במעבדה ולא נכרה מהאדמה.\n\nוזה מה שמאפשר טבעת סוליטר של 1.50 קראט בזהב 14K, ב־₪5,300.\n\nכל הפרטים באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "cover",
     "box": [
      86,
      67,
      993,
      418
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(213,196,181)",
     "scrim": "rgba(250,246,238,0.22)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "אותו יהלום.<br>בלי המכרה.",
     "sub": "יהלום מעבדה · 1.50 קראט · זהב 14K",
     "note": "שאלות על יהלומי מעבדה? תשאלי אותי.",
     "signature": "סתיו"
    }
   },
   {
    "no": 6,
    "angle": "A2",
    "format": "4:5",
    "img": "/reports/stav/raw_06.webp",
    "headline": "טבעת סוליטר 1.50 קראט",
    "primary": "יש טבעות שצריך להתקרב כדי לראות.\nוזו לא אחת מהן.\n\nחיתוך רדיאנט מוארך, שיבוץ כוס חלק מזהב 14K, ויהלום מעבדה של 1.50 קראט שתופס כל קרן אור.\n\nלהצעה, ליום נישואין, או פשוט כי מגיע לך.\n\nהטבעת באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "contrast",
     "box": [
      583,
      526,
      1015,
      904
     ],
     "top": false,
     "ink": "#f4ecdf",
     "paper": "rgb(0,6,7)",
     "scrim": "rgba(0,0,0,0.14)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "1.50 קראט<br>שרואים מכל החדר.",
     "sub": "",
     "note": "יש לך שאלות על יהלומי מעבדה? תשאלי אותי.",
     "signature": "סתיו"
    }
   },
   {
    "no": 7,
    "angle": "A2",
    "format": "1:1",
    "img": "/reports/stav/raw_07.webp",
    "headline": "יהלום מעבדה? זה יהלום אמיתי",
    "primary": "השאלה הראשונה ששואלים אותי על יהלומי מעבדה: זה אמיתי?\n\nכן. יהלום מעבדה בנוי מאותו חומר בדיוק כמו יהלום מהמכרה, עם אותו ברק ואותה קשיות.\n\nמה ששונה זה המחיר. ואת זה מרגישים רק בקופה.\n\nמוזמנת להציץ בקולקציה.",
    "cta": "Learn More",
    "spec": {
     "w": 1080,
     "h": 1080,
     "direction": "quiet",
     "box": [
      86,
      54,
      993,
      334
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(0,0,0)",
     "scrim": "rgba(0,0,0,0.14)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "זה לא זכוכית.<br>זה יהלום.",
     "sub": "",
     "note": "יש לך שאלות על יהלומי מעבדה? תשאלי אותי.",
     "signature": "סתיו"
    }
   },
   {
    "no": 8,
    "angle": "A2",
    "format": "9:16",
    "img": "/reports/stav/raw_08.webp",
    "headline": "שרשרת יהלום ב־1,500 ש״ח",
    "primary": "שרשרת זהב 14K עם יהלום מעבדה אחד, נקי, בשיבוץ ארבע שיניים.\n\nהיא הולכת עם ג'ינס, עם שמלת ערב ועם כל מה שביניהם. והיא לא יורדת מהצוואר.\n\n₪1,500, ומשלוח חינם בקנייה מעל ₪1,000.\n\nהשרשרת באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1920,
     "direction": "stack",
     "box": [
      86,
      250,
      993,
      749
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(64,41,29)",
     "scrim": "rgba(250,246,238,0.44)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "יהלום אמיתי.<br>1,500 ש״ח.",
     "sub": "יהלום מעבדה · זהב 14K",
     "note": "יש לך שאלות על יהלומי מעבדה? תשאלי אותי.",
     "signature": "סתיו"
    }
   },
   {
    "no": 9,
    "angle": "A3",
    "format": "4:5",
    "img": "/reports/stav/raw_09.webp",
    "headline": "מתנה שלא נשכחת אחרי שבוע",
    "primary": "רוב המתנות נשכחות אחרי שבוע.\n\nעגילי זהב עם ספיר כחול ויהלום היא תענוד שנים, ובכל פעם שמישהו ישאל עליהם, היא תספר ממי קיבלה אותם.\n\nאם אתה מחפש מתנה שלא תיעלם במגירה, תתחיל מכאן.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "note",
     "box": [
      86,
      67,
      993,
      364
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(58,49,41)",
     "scrim": "rgba(250,246,238,0.62)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "היא תזכור<br>מי נתן לה את זה.",
     "sub": "עגילי ספיר ויהלום · זהב 14K",
     "note": "צריך עזרה בבחירה? אני פה.",
     "signature": "סתיו"
    }
   },
   {
    "no": 10,
    "angle": "A3",
    "format": "4:5",
    "img": "/reports/stav/raw_10.webp",
    "headline": "המתנה לרגע שרוצים שייזכר",
    "primary": "יום נישואין, יום הולדת, או סתם ערב שרוצים שייזכר.\n\nשרשרת זהב 14K עם יהלום מעבדה אחד. עדינה מספיק לכל יום, מרשימה מספיק לרגע הזה.\n\nלא בטוח מה לבחור? אפשר לקפוץ לבוטיק בשינקין 48 ולהתייעץ.\n\nהשרשרת כאן.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "quiet",
     "box": [
      86,
      94,
      993,
      445
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(16,11,6)",
     "scrim": "rgba(0,0,0,0.66)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "שתדע<br>שחשבת עליה באמת.",
     "sub": "",
     "note": "צריך עזרה בבחירה? אני פה.",
     "signature": "סתיו"
    }
   },
   {
    "no": 11,
    "angle": "A3",
    "format": "1:1",
    "img": "/reports/stav/raw_11.webp",
    "headline": "הפרח שלא נובל",
    "primary": "השנה, במקום זר שייזרק בעוד שבוע,\nתן לה פרח שיישאר.\n\nתליון פרח מזהב 14K עם אמרלד טבעי בלב, בעבודת יד.\n\nהיא תענוד אותו ותחשוב עליך, הרבה אחרי שהזר היה נגמר.\n\nהתליון באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1080,
     "direction": "cover",
     "box": [
      86,
      54,
      993,
      291
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(50,42,36)",
     "scrim": "rgba(0,0,0,0.14)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "פרחים נובלים.<br>זהב נשאר.",
     "sub": "",
     "note": "צריך עזרה בבחירה? אני פה.",
     "signature": "סתיו"
    }
   },
   {
    "no": 12,
    "angle": "A3",
    "format": "9:16",
    "img": "/reports/stav/raw_12.webp",
    "headline": "עגילים שהיא לא תוריד",
    "primary": "המתנות הכי טובות לא נשארות בקופסה.\n\nעגילי שרשרת עדינים מזהב 14K, ספיר כחול ויהלום קטן. קלים מספיק ליום עבודה, מיוחדים מספיק לערב.\n\nומשלוח חינם בקנייה מעל ₪1,000.\n\nלפרטים.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1920,
     "direction": "contrast",
     "box": [
      432,
      250,
      1015,
      518
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(232,215,201)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "המתנה<br>שהיא תענוד כל יום.",
     "sub": "",
     "note": "צריך עזרה בבחירה? אני פה.",
     "signature": "סתיו"
    }
   },
   {
    "no": 13,
    "angle": "A4",
    "format": "4:5",
    "img": "/reports/stav/raw_13.webp",
    "headline": "קולקציית הפרחים החדשה",
    "primary": "פרח קטן מזהב, שמונה עלי כותרת, ואמרלד טבעי בלב.\n\nכאן הטבע פוגש עבודת יד: כל עלה מלוטש ביד, כל פרט מדויק.\n\nקולקציית הפרחים של סתיו, עכשיו באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "contrast",
     "box": [
      64,
      67,
      496,
      256
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(1,4,4)",
     "scrim": "rgba(0,0,0,0.14)",
     "plate_bg": null,
     "brand_color": "#f4ecdf",
     "obj_pos": "center",
     "plate": false,
     "headline": "טבע.<br>יצוק בזהב 14K.",
     "sub": "אמרלד טבעי · עבודת יד",
     "note": "הטבע הוא ההשראה שלי.",
     "signature": "סתיו"
    }
   },
   {
    "no": 14,
    "angle": "A4",
    "format": "4:5",
    "img": "/reports/stav/raw_14.webp",
    "headline": "התליון ששואלים עליו",
    "primary": "יש תכשיטים שאף אחד לא שם לב אליהם.\nויש כאלה ששואלים עליהם.\n\nתליון הפרח עם האמרלד הוא מהסוג השני. עדין, ובכל זאת אי אפשר לפספס אותו.\n\nזהב 14K, אמרלד טבעי, עבודת יד בסטודיו בתל אביב.\n\nמוזמנת לראות את כל הקולקציה.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "quiet",
     "box": [
      86,
      67,
      993,
      418
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(1,8,7)",
     "scrim": "rgba(0,0,0,0.14)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "תכשיט<br>שעוצרים עליו ברחוב.",
     "sub": "",
     "note": "הטבע הוא ההשראה שלי.",
     "signature": "סתיו"
    }
   },
   {
    "no": 15,
    "angle": "A4",
    "format": "1:1",
    "img": "/reports/stav/raw_15.webp",
    "headline": "אמרלד טבעי, זהב 14K",
    "primary": "לא זכוכית ולא אבן סינתטית.\nאמרלד טבעי, בלב של פרח מזהב 14K.\n\nמקולקציית הטבע של סתיו, בעבודת יד.\n\nלכל הקולקציה.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1080,
     "direction": "quiet",
     "box": [
      86,
      54,
      993,
      334
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(15,20,7)",
     "scrim": "rgba(250,246,238,0.56)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "אמרלד טבעי.<br>בלב של פרח.",
     "sub": "",
     "note": "הטבע הוא ההשראה שלי.",
     "signature": "סתיו"
    }
   },
   {
    "no": 16,
    "angle": "A4",
    "format": "9:16",
    "img": "/reports/stav/raw_16.webp",
    "headline": "קולקציית הטבע, מ־₪1,100",
    "primary": "פרחים, יונים ועלים. הקולקציה החדשה שלי נולדה מהטבע.\n\nשרשראות ועגילים מזהב 14K, משובצים באמרלד, רובי וספיר טבעיים, מ־₪1,100.\n\n5% הנחה בקנייה של 3 תכשיטים ומעלה.\n\nכל הקולקציה באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1920,
     "direction": "stack",
     "box": [
      86,
      250,
      993,
      518
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(242,235,233)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "גן שלם<br>על שרשרת אחת.",
     "sub": "",
     "note": "הטבע הוא ההשראה שלי.",
     "signature": "סתיו"
    }
   },
   {
    "no": 17,
    "angle": "A5",
    "format": "4:5",
    "img": "/reports/stav/raw_17.webp",
    "headline": "עיצוב אישי, האבן שאת בוחרת",
    "primary": "אהבת את הטבעת, אבל חלמת על ספיר? או רובי?\n\nאצלי אפשר. כל תכשיט אפשר להתאים: את האבן, את גוון הזהב ואת המידה.\n\nכי תכשיט שעוצב בשבילך הוא תכשיט שאין לאף אחת אחרת.\n\nלעיצוב אישי.",
    "cta": "Learn More",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "cover",
     "box": [
      86,
      67,
      993,
      364
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(11,12,15)",
     "scrim": "rgba(0,0,0,0.14)",
     "plate_bg": null,
     "brand_color": "#f4ecdf",
     "obj_pos": "center",
     "plate": false,
     "headline": "אותו עיצוב.<br>האבן שלך.",
     "sub": "ספיר · רובי · אמרלד · יהלום",
     "note": "ספרי לי מה את מדמיינת.",
     "signature": "סתיו"
    }
   },
   {
    "no": 18,
    "angle": "A5",
    "format": "4:5",
    "img": "/reports/stav/raw_18.webp",
    "headline": "טבעות בייצור מוגבל",
    "primary": "תכשיט מהקניון יש לעוד אלף נשים.\n\nאת הטבעות שלי אני מעצבת בייצור מוגבל, ואפשר להתאים כל אחת: אבן, גוון זהב, מידה.\n\nכך שהטבעת שעל היד שלך באמת שלך.\n\nלקולקציית הטבעות.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "quiet",
     "box": [
      86,
      67,
      993,
      418
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(235,233,231)",
     "scrim": "rgba(250,246,238,0.7)",
     "plate_bg": null,
     "brand_color": "#231a12",
     "obj_pos": "center",
     "plate": false,
     "headline": "הטבעת<br>שאין לאף אחת אחרת.",
     "sub": "",
     "note": "ספרי לי מה את מדמיינת.",
     "signature": "סתיו"
    }
   },
   {
    "no": 19,
    "angle": "A5",
    "format": "1:1",
    "img": "/reports/stav/raw_19.webp",
    "headline": "ספרי לי מה את מדמיינת",
    "primary": "כל תכשיט באתר אפשר להתאים אישית: ספיר, אמרלד, רובי או יהלום, בזהב צהוב, לבן או אדום.\n\nספרי לי מה את מדמיינת, ואני אעצב את זה.\n\nלעיצוב אישי.",
    "cta": "Learn More",
    "spec": {
     "w": 1080,
     "h": 1080,
     "direction": "stack",
     "box": [
      86,
      54,
      993,
      291
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(2,35,28)",
     "scrim": "rgba(0,0,0,0.14)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "רוצה אבן אחרת?<br>רק תגידי.",
     "sub": "",
     "note": "ספרי לי מה את מדמיינת.",
     "signature": "סתיו"
    }
   },
   {
    "no": 20,
    "angle": "A5",
    "format": "9:16",
    "img": "/reports/stav/raw_20.webp",
    "headline": "עגילים באבן שאת בוחרת",
    "primary": "אותם עגילים, שלוש אישיויות.\n\nספיר כחול לקלאסיקה. אמרלד ירוק לנועזות. רובי אדום למי שלא מתנצלת.\n\nעגילי שרשרת מזהב 14K עם יהלום קטן, בהתאמה אישית.\n\nבחרי את שלך.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1920,
     "direction": "note",
     "box": [
      86,
      250,
      993,
      576
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(244,228,220)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "plate": false,
     "headline": "ספיר, אמרלד או רובי?<br>את בוחרת.",
     "sub": "",
     "note": "ספרי לי מה את מדמיינת.",
     "signature": "סתיו"
    }
   }
  ],
  "hero": [
   14,
   5,
   11,
   20
  ],
  "hero_bg": "/reports/stav/hero.webp",
  "contact_url": "https://wa.me/972545471522",
  "cta": {
   "eyebrow": "מאיתנו, בשבילך",
   "title": [
    "סתיו, את כל זה הכנו בשבילך.",
    "בחינם, בלי התחייבות."
   ],
   "text": "רצינו להראות לך מה אפשר לעשות עם המותג שלך, לפני שמדברים על כסף. אם נעבוד יחד, זו רק נקודת ההתחלה: נעלה את המודעות, נבדוק מה מוכר הכי טוב, ונגדיל את מה שעובד.",
   "button": "בואי נדבר בוואטסאפ"
  },
  "hero_eyebrow": "קולקציית הטבע · זהב 14K · אמרלד טבעי",
  "hero_title": [
   "פרחים נובלים.",
   "זהב נשאר."
  ],
  "strip": [
   1,
   5,
   11,
   14,
   17,
   20,
   7,
   10
  ],
  "review": {
   "eyebrow": "עברנו על הקמפיין שלך",
   "title": [
    "הקמפיין שלך עובד.",
    "והוא יכול להכניס הרבה יותר."
   ],
   "text": "המודעות שלך כבר מוכרות: חלקן רצות יותר משנה, וזה בדרך כלל סימן שהן מביאות כסף. עברנו עליהן, על האתר ועל הקולקציות. ככה זה נראה היום, וככה אנחנו היינו עושים את זה.",
   "issues_eyebrow": "מה היינו משנים",
   "issues": [
    "ארבעה דברים",
    "שהיינו משנים כבר מחר."
   ]
  },
  "split": {
   "ad": 5,
   "eyebrow": "יהלום מעבדה",
   "title": [
    "אותו יהלום.",
    "אותו ברק.",
    "בלי המכרה."
   ],
   "text": "סוליטר 1.50 קראט בחיתוך רדיאנט מוארך, בשיבוץ כוס חלק מזהב 14K. אותו פחמן, אותה קשיות, אותו ברק.",
   "price": "5,300 ש״ח"
  },
  "band": {
   "ad": 3,
   "quote": "כל תכשיט מתחיל אצלי בסקיצה.",
   "by": "סתיו תכשיטי יוקרה · שינקין 48, תל אביב"
  },
  "compare": {
   "before": {
    "label": "ככה זה נראה היום",
    "items": [
     {
      "img": "/reports/stav/cur_01.webp",
      "w": 720,
      "h": 720,
      "video": true
     },
     {
      "img": "/reports/stav/cur_02.webp",
      "w": 1080,
      "h": 1080,
      "video": false
     },
     {
      "img": "/reports/stav/cur_03.webp",
      "w": 1080,
      "h": 1080,
      "video": false
     },
     {
      "img": "/reports/stav/cur_04.webp",
      "w": 1080,
      "h": 1080,
      "video": false
     }
    ]
   },
   "after": {
    "label": "וככה אנחנו היינו עושים את זה",
    "ads": [
     1,
     18,
     5,
     13
    ]
   }
  },
  "hero_bg_m": "/reports/stav/hero_m.webp",
  "hero_pos_m": "center top"
 },
 "bscents-97198747": {
  "slug": "bscents-97198747",
  "ads": [
   {
    "no": 1,
    "angle": "A1",
    "format": "4:5",
    "img": "/reports/bscents/raw_01.webp",
    "headline": "ריח של מלון בוטיק בבית",
    "primary": "יש רגע כזה כשנכנסים ללובי של מלון טוב. הריח עוטף אתכם עוד לפני שמישהו אמר שלום.\n\nעכשיו הרגע הזה מחכה לכם בכניסה הביתה.\n\nמפיץ הריח החשמלי B-150 של בי סנטס מאדה תמצית שמן בושם טהורה, בלי מים ובלי אלכוהול, וממלא חללים עד 150 מ״ר.\n\nבוחרים ריח, מכוונים שעות מהנייד, ושוכחים ממנו.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "contrast",
     "box": [
      432,
      67,
      1015,
      364
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(222,211,199)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "ריח של לובי מלון.<br>בכניסה שלכם.",
     "sub": "מפיץ ריח חשמלי · עד 150 מ״ר",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 2,
    "angle": "A1",
    "format": "4:5",
    "img": "/reports/bscents/raw_02.webp",
    "headline": "הבית שלכם, בגרסת המלון",
    "primary": "אתם מכירים את התחושה הזאת בחדר של מלון טוב? הכול שקט, נקי, והריח עושה חצי מהעבודה.\n\nאפשר להרגיש ככה גם בבית, כל יום.\n\nמפיצי הריח של בי סנטס עובדים על אידוי שמן בושם טהור, והריח נשאר בחלל גם אחרי שהמכשיר כבוי.\n\nמגוון ניחוחות בהשראת מלונות וחנויות יוקרה, באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "quiet",
     "box": [
      86,
      67,
      993,
      418
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(215,208,201)",
     "scrim": "rgba(250,246,238,0.24)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "נכנסים הביתה.<br>ומרגישים בחופשה.",
     "sub": "ריח שנשאר בחלל גם כשהמכשיר כבוי",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 3,
    "angle": "A1",
    "format": "9:16",
    "img": "/reports/bscents/raw_03.webp",
    "headline": "מלון חמישה כוכבים. בסלון.",
    "primary": "לא צריך להזמין חדר כדי להרגיש כמו במלון חמישה כוכבים.\n\nמספיק מכשיר אחד על הקיר ושמן בושם שנבחר בקפידה.\n\nה-B-150 בשחור של בי סנטס משתלב בכל עיצוב, ומפזר ריח עשיר ומורגש בחללים עד 150 מ״ר.\n\nבואו לבחור את הניחוח של הבית שלכם.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1920,
     "direction": "stack",
     "box": [
      86,
      250,
      993,
      518
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(14,7,5)",
     "scrim": "rgba(0,0,0,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "חמישה כוכבים.<br>בלי צ׳ק אאוט.",
     "sub": "שמן בושם 100% · בלי מים",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 4,
    "angle": "A1",
    "format": "4:5",
    "img": "/reports/bscents/raw_04.webp",
    "headline": "ריח שנשאר בחלל",
    "primary": "רוב מפיצי הריח מפזרים בעיקר אדים. אנחנו מפזרים בושם.\n\nשמני הבושם של בי סנטס הם 100% תמצית, בלי מים ובלי אלכוהול, ועומדים בתקני IFRA ו-SDS.\n\nלכן הריח לא נעלם כשהמכשיר נכבה. הוא נשאר בחלל.\n\nעשרות ניחוחות לבחירה, 500 מ״ל ב-179 ש״ח.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "cover",
     "box": [
      86,
      67,
      993,
      364
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(223,216,208)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "ריח שנשאר<br>גם כשהמכשיר כבוי.",
     "sub": "100% תמצית שמן בושם · 500 מ״ל",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 5,
    "angle": "A2",
    "format": "4:5",
    "img": "/reports/bscents/raw_05.webp",
    "headline": "כביסה שמריחה כמו בושם",
    "primary": "נכון שתמיד חלמתם שהריח יישאר על הכביסה? גם אחרי המייבש, גם אחרי שבוע בארון.\n\nתמצית שמן הבושם לכביסה של בי סנטס נכנסת לתא המרכך במקום המרכך, ומבשמת ומרככת בבת אחת.\n\n100% תמצית בושם, בלי כתמים.\n\n200 מ״ל ב-44 ש״ח, במגוון ניחוחות.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "stack",
     "box": [
      86,
      94,
      993,
      391
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(210,201,194)",
     "scrim": "rgba(250,246,238,0.18)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "הכביסה<br>שמריחה כמו בושם.",
     "sub": "תמצית שמן בושם לכביסה · 200 מ״ל",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 6,
    "angle": "A2",
    "format": "1:1",
    "img": "/reports/bscents/raw_06.webp",
    "headline": "הריח לא נעלם אחרי הייבוש",
    "primary": "הכביסה יוצאת מהמכונה ומריחה נהדר. יום אחרי, כבר לא.\n\nעם תמצית שמן הבושם לכביסה של בי סנטס זה נגמר: הריח נאחז בבד ונשאר גם אחרי הייבוש וגם בארון.\n\nשופכים 10 עד 20 מ״ל לתא המרכך, וזהו.\n\nמגוון ניחוחות באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1080,
     "direction": "contrast",
     "box": [
      64,
      54,
      496,
      356
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(237,237,237)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": "#231a12",
     "obj_pos": "center",
     "headline": "ריח שנשאר<br>גם בארון.",
     "sub": "גם אחרי המייבש",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 7,
    "angle": "A2",
    "format": "9:16",
    "img": "/reports/bscents/raw_07.webp",
    "headline": "מארז כל הריחות לכביסה",
    "primary": "לא יודעים איזה ריח לבחור? לא צריך.\n\nבמארז כל הריחות של בי סנטס מקבלים את כל 11 הניחוחות לכביסה: מפרחוני ועד רענן, מבושם יוקרתי ועד ריח של כביסה של פעם.\n\n11 בקבוקים של 200 מ״ל ב-395 ש״ח.\n\nכל כביסה, ריח אחר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1920,
     "direction": "contrast",
     "box": [
      64,
      250,
      648,
      672
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(229,227,225)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": "#231a12",
     "obj_pos": "center",
     "headline": "11 ניחוחות.<br>לכל מצב רוח.",
     "sub": "מארז כל הריחות · 11 × 200 מ״ל",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 8,
    "angle": "A2",
    "format": "4:5",
    "img": "/reports/bscents/raw_08.webp",
    "headline": "10 מ״ל. כל הכביסה מריחה.",
    "primary": "מרכך כביסה רגיל מכיל 5% עד 10% תמצית בושם. השאר זה מים וחומרים.\n\nאצלנו זה 100% תמצית שמן בושם.\n\nלכן מספיקים 10 עד 20 מ״ל בתא המרכך כדי שכל הכביסה תריח ימים.\n\nנסו בקבוק אחד ב-44 ש״ח ותרגישו את ההבדל.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "quiet",
     "box": [
      86,
      67,
      993,
      418
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(230,226,222)",
     "scrim": "rgba(250,246,238,0.22)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "10 מ״ל במקום המרכך.<br>זה כל הסוד.",
     "sub": "מגיע עם כוס מדידה",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 9,
    "angle": "A3",
    "format": "4:5",
    "img": "/reports/bscents/raw_09.webp",
    "headline": "ריח מותג לעסק שלכם",
    "primary": "לקוחות לא תמיד זוכרים מה קנו. הם זוכרים איך הרגישו.\n\nוחוש הריח הוא הקיצור הכי מהיר לזיכרון.\n\nה-B-420 של בי סנטס ממלא חללים עד 420 מ״ר, נשלט מהנייד ב-Wi-Fi, ואפשר גם לפזר דרכו ריח דרך המיזוג.\n\nרוצים ריח מותג משלכם? דברו איתנו.",
    "cta": "Learn More",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "cover",
     "box": [
      86,
      67,
      993,
      418
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(229,221,215)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "לקוחות זוכרים<br>איך המקום הריח.",
     "sub": "לעסקים · עד 420 מ״ר",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 10,
    "angle": "A3",
    "format": "1:1",
    "img": "/reports/bscents/raw_10.webp",
    "headline": "בישום מקצועי לעסקים",
    "primary": "לפני שמישהו אמר שלום, הלקוח כבר קיבל רושם ראשון.\n\nבי סנטס מספקת מערכות ריח ושמני בושם לבתי מלון, לחנויות, לקליניקות ולמשרדים, בהתאמה לחלל ולאופי המקום.\n\nמכשירים חסכוניים, שליטה מהנייד, וריח שנשאר.\n\nלהזמנות בסיטונאות ולריח בהתאמה אישית, השאירו פרטים.",
    "cta": "Learn More",
    "spec": {
     "w": 1080,
     "h": 1080,
     "direction": "contrast",
     "box": [
      583,
      54,
      1015,
      356
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(218,208,199)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "הריח הוא<br>קבלת הפנים.",
     "sub": "בישום מקצועי לעסקים",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 11,
    "angle": "A3",
    "format": "9:16",
    "img": "/reports/bscents/raw_11.webp",
    "headline": "ריח אחיד לחללים גדולים",
    "primary": "חלל גדול צריך מכשיר רציני.\n\nה-B-420 של בי סנטס מפזר ריח אחיד בחללים עד 420 מ״ר, עם מאוורר פנימי וחיצוני ושליטה מהנייד ב-Wi-Fi או ב-Bluetooth.\n\nמכוונים עוצמה, ימים ושעות, והמכשיר עובד לבד.\n\nלקליניקות, ללובים, לחנויות ולמשרדים.",
    "cta": "Learn More",
    "spec": {
     "w": 1080,
     "h": 1920,
     "direction": "contrast",
     "box": [
      432,
      250,
      1015,
      672
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(223,219,215)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "עד 420 מ״ר<br>של ריח אחד מדויק.",
     "sub": "שליטה מלאה מהנייד",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 12,
    "angle": "A3",
    "format": "4:5",
    "img": "/reports/bscents/raw_12.webp",
    "headline": "הריח שמנהל את עצמו",
    "primary": "יש לכם מספיק דברים לנהל בעסק. הריח לא צריך להיות אחד מהם.\n\nבמפיצי הריח של בי סנטס מכוונים מראש עוצמה ושעות פעילות, אפשר להגדיר כל יום אחרת, והכול מהנייד.\n\nואם תרצו, אנחנו נכוון בשבילכם עוד לפני שהמכשיר יוצא אליכם.\n\nבואו לדבר על הריח של העסק.",
    "cta": "Learn More",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "contrast",
     "box": [
      64,
      67,
      496,
      364
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(55,36,23)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "מכוונים פעם אחת.<br>הריח עובד לבד.",
     "sub": "תזמון ימים ושעות מהנייד",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 13,
    "angle": "A4",
    "format": "4:5",
    "img": "/reports/bscents/raw_13.webp",
    "headline": "ריח אמיתי, בלי אדים",
    "primary": "מפיץ אדים מפזר בעיקר מים. אתם מקבלים לחות, ומעט מאוד ריח.\n\nמפיצי הריח של בי סנטס עובדים על אידוי תמצית שמן בושם טהורה, בלי מים, בלי גז ובלי אלכוהול.\n\nהתוצאה: ריח מורגש באמת, בלי אדים ובלי כתמים.\n\nה-B-25 הקומפקטי, לחללים עד 25 מ״ר, ב-329 ש״ח.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "quiet",
     "box": [
      86,
      67,
      993,
      418
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(68,52,37)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "בלי מים.<br>בלי אדים. רק ריח.",
     "sub": "טכנולוגיית אידוי שמן בושם",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 14,
    "angle": "A4",
    "format": "1:1",
    "img": "/reports/bscents/raw_14.webp",
    "headline": "הריח בזמן שלכם",
    "primary": "רוצים שהבית יריח טוב כשאתם חוזרים, ושקט בלילה?\n\nעם מפיצי הריח של בי סנטס מתזמנים ימים, שעות ועוצמה ישר מהנייד, וכל יום יכול להיראות אחרת.\n\nה-B-25 עובד על חשמל או על סוללות, ונתלה בלי קידוח.\n\nכל הדגמים באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1080,
     "direction": "stack",
     "box": [
      86,
      54,
      993,
      291
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(218,213,207)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "ריח לפי לוח זמנים.<br>שלכם.",
     "sub": "שליטה מהנייד",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 15,
    "angle": "A4",
    "format": "9:16",
    "img": "/reports/bscents/raw_15.webp",
    "headline": "ריח שממלא את החלל",
    "primary": "קניתם פעם מפיץ ריח ואחרי יומיים כבר לא הרגשתם כלום?\n\nה-B-150 של בי סנטס בנוי אחרת: מאוורר פנימי, משאבה מחוזקת ואידוי שמן בושם טהור, לחללים עד 150 מ״ר.\n\nהוא חסכוני בשמן ובחשמל, ומגיע עם 100 מ״ל שמן בושם.\n\n599 ש״ח, באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1920,
     "direction": "cover",
     "box": [
      86,
      250,
      993,
      576
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(211,200,190)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "ריח שממלא<br>את כל החלל.",
     "sub": "עד 150 מ״ר · 599 ש״ח",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 16,
    "angle": "A4",
    "format": "4:5",
    "img": "/reports/bscents/raw_16.webp",
    "headline": "איך נשמע ריח יוקרתי",
    "primary": "הסוד הוא לא רק בריח. הוא באיך שהוא מתפזר.\n\nהמכשירים של בי סנטס מאדים תמצית שמן בושם לחלקיקים זעירים שממלאים את החלל, בלי מים ובלי אלכוהול.\n\nהשמנים שלנו עומדים בתקנים המחמירים של IFRA ו-SDS.\n\nריח עשיר, מורגש, ובטוח.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "contrast",
     "box": [
      583,
      67,
      1015,
      445
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(22,20,20)",
     "scrim": "rgba(0,0,0,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": "#f4ecdf",
     "obj_pos": "center",
     "headline": "טכנולוגיית אידוי<br>של שמן בושם טהור.",
     "sub": "עומד בתקני בטיחות בינלאומיים",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 17,
    "angle": "A5",
    "format": "4:5",
    "img": "/reports/bscents/raw_17.webp",
    "headline": "ריח של מלון, בנסיעה",
    "primary": "הרכב הוא החדר שאתם מבלים בו הכי הרבה זמן בלי לשים לב.\n\nה-TO-CAR של בי סנטס נכנס למחזיק הכוסות, נטען ב-USB, ומפזר שמן בושם אמיתי בשלוש עוצמות.\n\nמגיע עם שני בקבוקוני שמן בושם של 15 מ״ל.\n\n299 ש״ח, באתר.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "cover",
     "box": [
      86,
      67,
      993,
      418
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(27,24,25)",
     "scrim": "rgba(0,0,0,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": "#f4ecdf",
     "obj_pos": "center",
     "headline": "הריח שלכם<br>נוסע איתכם.",
     "sub": "מפיץ ריח נטען לרכב",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 18,
    "angle": "A5",
    "format": "1:1",
    "img": "/reports/bscents/raw_18.webp",
    "headline": "ליאו. בושם לגבר.",
    "primary": "בושם שנשאר איתכם כל היום, ולא נעלם עד הצהריים.\n\nליאו של בי סנטס מיוצר בישראל, מחומרי גלם שנבחרו בקפידה, בבקבוק שנראה טוב על כל שיש.\n\n100 מ״ל ב-289 ש״ח, ומגיעה איתו דוגמית במתנה.\n\nלגבר שיודע מה הוא לובש.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1080,
     "direction": "contrast",
     "box": [
      583,
      54,
      1015,
      356
     ],
     "top": true,
     "ink": "#f4ecdf",
     "paper": "rgb(6,8,10)",
     "scrim": "rgba(0,0,0,0.22)",
     "plate": false,
     "plate_bg": null,
     "brand_color": "#f4ecdf",
     "obj_pos": "center",
     "headline": "ליאו.<br>בושם לגבר. מיוצר בישראל.",
     "sub": "100 מ״ל · 289 ש״ח",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 19,
    "angle": "A5",
    "format": "9:16",
    "img": "/reports/bscents/raw_19.webp",
    "headline": "לייה. בושם לאישה.",
    "primary": "יש בשמים שמריחים. ויש בשמים שזוכרים.\n\nלייה של בי סנטס: פרחוני, מתקתק ורענן, עם תווי מנדרינה, פריחת תפוז, וניל ודבש.\n\nמיוצר בישראל, 100 מ״ל ב-289 ש״ח, עם דוגמית במתנה.\n\nפינוק לעצמך, או מתנה למישהי שאוהבים.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1920,
     "direction": "contrast",
     "box": [
      583,
      250,
      1015,
      672
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(17,1,1)",
     "scrim": "rgba(250,246,238,0.14)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "לייה.<br>נשיות עם חתימה.",
     "sub": "100 מ״ל · מיוצר בישראל",
     "note": null,
     "signature": null
    }
   },
   {
    "no": 20,
    "angle": "A5",
    "format": "4:5",
    "img": "/reports/bscents/raw_20.webp",
    "headline": "המפיץ שנכבה לבד",
    "primary": "מפיץ ריח לרכב שחושב בשבילכם.\n\nל-TO-CAR של בי סנטס יש חיישן תזוזה: כשהרכב זז הוא עובד, ואחרי 5 דקות בלי תנועה הוא נכבה לבד.\n\nשלוש עוצמות ריח, תאורת לד עדינה, וסוללה נטענת.\n\nבשחור או בזהב, ב-299 ש״ח.",
    "cta": "Shop Now",
    "spec": {
     "w": 1080,
     "h": 1350,
     "direction": "contrast",
     "box": [
      583,
      67,
      1015,
      445
     ],
     "top": true,
     "ink": "#1f1812",
     "paper": "rgb(209,199,188)",
     "scrim": "rgba(250,246,238,0.26)",
     "plate": false,
     "plate_bg": null,
     "brand_color": null,
     "obj_pos": "center",
     "headline": "5 דקות בלי תזוזה?<br>הוא נכבה לבד.",
     "sub": "חיישן תנועה מובנה",
     "note": null,
     "signature": null
    }
   }
  ],
  "hero_bg": "/reports/bscents/hero.webp",
  "business": {
   "name": "בי סנטס",
   "wordmark": "בי סנטס",
   "site": "https://b-scents.co.il/"
  },
  "hero_eyebrow": "מפיצי ריח חשמליים · שמני בושם · בישום לכביסה",
  "hero_title": [
   "ריח של מלון.",
   "בבית שלכם."
  ],
  "hero_bg_m": "/reports/bscents/hero_m.webp",
  "hero_pos_m": "0% 0%",
  "hero_cta_m": "bottom",
  "hero_cta": "מה היינו משנים בקמפיין שלכם",
  "review": {
   "eyebrow": "עברנו על הקמפיין שלכם",
   "title": [
    "הקמפיין שלכם עובד.",
    "והוא יכול להכניס הרבה יותר."
   ],
   "text": "המודעות שלכם כבר מוכרות: חלקן רצות יותר מחצי שנה, וזה בדרך כלל סימן שהן מביאות כסף. עברנו עליהן, על האתר ועל המוצרים. ככה זה נראה היום, וככה אנחנו היינו עושים את זה.",
   "issues_eyebrow": "מה היינו משנים",
   "issues": [
    "ארבעה דברים",
    "שהיינו משנים כבר מחר."
   ],
   "next": "לקמפיין שבנינו בשבילכם"
  },
  "insights": [
   {
    "t": "הסרטונים שלכם עובדים",
    "d": "סרטוני ה-UGC עם אנשים אמיתיים רצים אצלכם כבר ארבעה עד שבעה חודשים. זה סימן חזק שהקהל מאמין לפנים ולחוויה."
   },
   {
    "t": "המוצר המבדל לא מקבל במה",
    "d": "11 מתוך 15 המודעות הפעילות מקדמות בישום לכביסה. מפיץ הריח החשמלי, המוצר הייחודי שלכם, מופיע רק בשתיים."
   },
   {
    "t": "אין עדיין ויזואל יוקרתי",
    "d": "אתם מוכרים ריח של מלון, אבל כל המודעות מצולמות בטלפון. אין תמונה אחת שמראה את המכשיר בבית או בעסק שנראים כמו מלון."
   },
   {
    "t": "עסקים ורכב מחוץ לתמונה",
    "d": "המכשיר לחללים של עד 420 מ״ר, הבישום בהתאמה אישית לעסקים והמפיץ לרכב לא מקבלים אף מודעה, למרות שכל אחד מהם הוא קהל חדש."
   }
  ],
  "angles": [
   {
    "id": "A1",
    "name": "ריח של מלון, בבית",
    "hook": "חמישה כוכבים. בלי צ׳ק אאוט.",
    "idea": "זו ההבטחה שאתם כבר מוכרים, עם ריחות בהשראת מלונות. כאן היא מקבלת תמונה: המכשיר כאובייקט עיצובי בבית שמרגיש כמו לובי של מלון בוטיק."
   },
   {
    "id": "A2",
    "name": "הכביסה שמריחה כמו בושם",
    "hook": "ריח שנשאר גם בארון.",
    "idea": "המוצר שכבר עובד לכם במודעות, בשפה ויזואלית נקייה ויוקרתית שמצדיקה מחיר ובונה מותג, ולא רק מבצע."
   },
   {
    "id": "A3",
    "name": "ריח שלקוחות זוכרים",
    "hook": "לקוחות זוכרים איך המקום הריח.",
    "idea": "קמפיין לעסקים: חנויות, קליניקות וקבלות של מלונות. קהל עם תקציב, רכישות חוזרות של מילוי, ואפשרות לריח מותג בהתאמה אישית."
   },
   {
    "id": "A4",
    "name": "בלי מים. בלי אדים. רק ריח.",
    "hook": "ריח שמרגישים מהרגע הראשון.",
    "idea": "הטכנולוגיה כיתרון: אידוי שמן בושם טהור, שליטה מהנייד ותזמון לפי ימים ושעות. תשובה ישירה לשאלה הכי גדולה של הקונים: זה בכלל מורגש?"
   },
   {
    "id": "A5",
    "name": "הריח שלכם, לאן שתלכו",
    "hook": "הריח שלכם נוסע איתכם.",
    "idea": "המפיץ לרכב והבשמים ליאו ולייה: מוצרים שכבר קיימים באתר ולא מקבלים חשיפה, ומרחיבים את הסל ואת עונת המתנות."
   }
  ],
  "compare": {
   "before": {
    "label": "ככה זה נראה היום",
    "items": [
     {
      "img": "/reports/bscents/cur_01.webp",
      "w": 1080,
      "h": 1920,
      "video": true
     },
     {
      "img": "/reports/bscents/cur_02.webp",
      "w": 1080,
      "h": 1920,
      "video": true
     },
     {
      "img": "/reports/bscents/cur_03.webp",
      "w": 2160,
      "h": 2160,
      "video": true
     },
     {
      "img": "/reports/bscents/cur_04.webp",
      "w": 1080,
      "h": 1920,
      "video": true
     }
    ]
   },
   "after": {
    "label": "וככה אנחנו היינו עושים את זה",
    "ads": [
     1,
     8,
     5,
     7
    ]
   }
  },
  "strip": [
   1,
   15,
   5,
   9,
   17,
   19,
   13,
   3
  ],
  "split": {
   "ad": 15,
   "eyebrow": "הדגל שלכם",
   "title": [
    "ריח שממלא",
    "את כל",
    "החלל."
   ],
   "text": "עד 150 מ״ר. אידוי תמצית שמן בושם בלי מים, בלי גז ובלי אלכוהול. תזמון ימים ושעות ישר מהנייד, וריח שנשאר בחלל גם כשהמכשיר כבוי.",
   "price": "599 ש״ח · כולל 100 מ״ל שמן בושם"
  },
  "band": {
   "ad": 16,
   "quote": "ריח הוא הדרך הקצרה ביותר לזיכרון.",
   "by": "בי סנטס · פתרונות בישום מתקדמים"
  },
  "cta": {
   "eyebrow": "מאיתנו, בשבילכם",
   "title": [
    "את כל זה הכנו בשבילכם.",
    "בחינם, בלי התחייבות."
   ],
   "text": "רצינו להראות לכם מה אפשר לעשות עם המותג שלכם, לפני שמדברים על כסף. אם נעבוד יחד, זו רק נקודת ההתחלה: נעלה את המודעות, נבדוק מה מוכר הכי טוב, ונגדיל את מה שעובד.",
   "button": "בואו נדבר בוואטסאפ"
  },
  "contact_url": "https://wa.me/972545471522"
 }
};
