import ClientPitch from "@/pages/ClientPitch";

// Client page for עלי כריים — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/alikarim-5c8e2d71
export default function AliKarim() {
  return <ClientPitch slug="alikarim-5c8e2d71" />;
}
