import ClientPitch from "@/pages/ClientPitch";

// Client page for אסטאין — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/astain-3f8c21d7
export default function AstaIn() {
  return <ClientPitch slug="astain-3f8c21d7" />;
}
