import ClientPitch from "@/pages/ClientPitch";

// Client page for בילי — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/billy-264ffd4c
export default function Billy() {
  return <ClientPitch slug="billy-264ffd4c" />;
}
