import ClientPitch from "@/pages/ClientPitch";

// Client page for בי סנטס — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/bscents-97198747
export default function BScents() {
  return <ClientPitch slug="bscents-97198747" />;
}
