import ClientPitch from "@/pages/ClientPitch";

// Client page for גלי ריפוי — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/gali-d71a3f58
export default function GaliRipui() {
  return <ClientPitch slug="gali-d71a3f58" />;
}
