import ClientPitch from "@/pages/ClientPitch";

// Client page for הייר קוסמטיקס — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/haircosmetics-8b8eb022
export default function HairCosmetics() {
  return <ClientPitch slug="haircosmetics-8b8eb022" />;
}
