import ClientPitch from "@/pages/ClientPitch";

// Client page for איתי אלבז — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/itai-4b1e7c93
export default function ItaiElbaz() {
  return <ClientPitch slug="itai-4b1e7c93" />;
}
