import ClientPitch from "@/pages/ClientPitch";

// Client page for ג׳קסון תכשיטים — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/jackson-18bceed3
export default function Jackson() {
  return <ClientPitch slug="jackson-18bceed3" />;
}
