import ClientPitch from "@/pages/ClientPitch";

// Client page for ג׳ולרי פקטורי — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/jewelryfactory-8d2e61b4
export default function JewelryFactory() {
  return <ClientPitch slug="jewelryfactory-8d2e61b4" />;
}
