import ClientPitch from "@/pages/ClientPitch";

// Client page for קלהרי רוז — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/kalahari-7c3e91d5
export default function Kalahari() {
  return <ClientPitch slug="kalahari-7c3e91d5" />;
}
