import ClientPitch from "@/pages/ClientPitch";

// Client page for כלב טבע — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/kelevteva-369078b4
export default function KelevTeva() {
  return <ClientPitch slug="kelevteva-369078b4" />;
}
