import ClientPitch from "@/pages/ClientPitch";

// Client page for מגה פט — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/megapet-beb32c3c
export default function MegaPet() {
  return <ClientPitch slug="megapet-beb32c3c" />;
}
