import ClientPitch from "@/pages/ClientPitch";

// Client page for מיי דיל — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/mydeal-5b7e19c2
export default function MyDeal() {
  return <ClientPitch slug="mydeal-5b7e19c2" />;
}
