import ClientPitch from "@/pages/ClientPitch";

// Client page for פט בסט — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/petbest-20bd483a
export default function PetBest() {
  return <ClientPitch slug="petbest-20bd483a" />;
}
