import ClientPitch from "@/pages/ClientPitch";

// Client page for רד סטאר — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/redstar-02f7aee4
export default function RedStar() {
  return <ClientPitch slug="redstar-02f7aee4" />;
}
