import ClientPitch from "@/pages/ClientPitch";

// Client page for מרכז רפאל — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/rephael-6e2b90c4
export default function Rephael() {
  return <ClientPitch slug="rephael-6e2b90c4" />;
}
