import ClientPitch from "@/pages/ClientPitch";

// Client page for סתיו תכשיטי יוקרה — its own page file so it appears as a page in the Base44 editor.
// Generated by the IL-meta-leads pipeline. Link: /p/stav-56f5e275
export default function Stav() {
  return <ClientPitch slug="stav-56f5e275" />;
}
