import { Toaster } from "@/components/ui/toaster"
import { QueryClientProvider } from '@tanstack/react-query'
import { queryClientInstance } from '@/lib/query-client'
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import PageNotFound from './lib/PageNotFound';
import { AuthProvider, useAuth } from '@/lib/AuthContext';
import UserNotRegisteredError from '@/components/UserNotRegisteredError';
import ScrollToTop from './components/ScrollToTop';
import Home from '@/pages/Home';
import ClientPitch from '@/pages/ClientPitch';
import Admin from '@/pages/Admin';
import Stav from '@/pages/Stav';
import BScents from '@/pages/BScents';
import AstaIn from '@/pages/AstaIn';
import JewelryFactory from '@/pages/JewelryFactory';
import MyDeal from '@/pages/MyDeal';
import HairCosmetics from '@/pages/HairCosmetics';
import Jackson from '@/pages/Jackson';

// Public site: a home page (content coming) + one standalone page per client at /p/<unguessable-slug>.
// No menus, no lists: a client only ever sees their own page.
const AuthenticatedApp = () => {
  const { isLoadingAuth, isLoadingPublicSettings, authError, navigateToLogin } = useAuth();

  if (isLoadingPublicSettings || isLoadingAuth) {
    return (
      <div className="fixed inset-0 flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-stone-300 border-t-stone-800 rounded-full animate-spin"></div>
      </div>
    );
  }

  if (authError) {
    if (authError.type === 'user_not_registered') {
      return <UserNotRegisteredError />;
    } else if (authError.type === 'auth_required') {
      navigateToLogin();
      return null;
    }
  }

  return (
    <Routes>
      <Route path="/" element={<Home />} />
      {/* Eran's private index of client pages (guarded inside the page: admin only) */}
      <Route path="/admin" element={<Admin />} />
      {/* One page file + literal route per client so each shows up as its own page in the Base44 editor.
          CLIENT-ROUTES:START (generated by the IL-meta-leads pipeline) */}
      <Route path="/p/stav-56f5e275" element={<Stav />} />
      <Route path="/p/bscents-97198747" element={<BScents />} />
      <Route path="/p/astain-3f8c21d7" element={<AstaIn />} />
      <Route path="/p/jewelryfactory-8d2e61b4" element={<JewelryFactory />} />
      <Route path="/p/mydeal-5b7e19c2" element={<MyDeal />} />
      <Route path="/p/haircosmetics-8b8eb022" element={<HairCosmetics />} />
      <Route path="/p/jackson-18bceed3" element={<Jackson />} />
      {/* CLIENT-ROUTES:END */}
      <Route path="/p/:slug" element={<ClientPitch />} />
      <Route path="*" element={<PageNotFound />} />
    </Routes>
  );
};

function App() {
  return (
    <AuthProvider>
      <QueryClientProvider client={queryClientInstance}>
        <Router>
          <ScrollToTop />
          <AuthenticatedApp />
        </Router>
        <Toaster />
      </QueryClientProvider>
    </AuthProvider>
  )
}

export default App
