import { Toaster } from "@/components/ui/toaster"
import { QueryClientProvider } from '@tanstack/react-query'
import { queryClientInstance } from '@/lib/query-client'
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import PageNotFound from './lib/PageNotFound';
import { AuthProvider, useAuth } from '@/lib/AuthContext';
import UserNotRegisteredError from '@/components/UserNotRegisteredError';
import ScrollToTop from './components/ScrollToTop';
import Home from '@/pages/Home';
import ClientPitch from '@/pages/ClientPitch';
import Admin from '@/pages/Admin';
import Crm from '@/pages/Crm';
import Login from '@/pages/Login';
import Register from '@/pages/Register';
import ForgotPassword from '@/pages/ForgotPassword';
import ResetPassword from '@/pages/ResetPassword';

// The SDK sends people to /login?from_url=<full url>, but the login page reads ?returnTo=<path>.
// Translate once (same-origin paths only) so a login from /crm lands back on /crm.
function LoginRoute() {
  const q = new URLSearchParams(window.location.search);
  const from = q.get('from_url');
  if (from && !q.get('returnTo')) {
    try {
      const u = new URL(from, window.location.origin);
      if (u.origin === window.location.origin) {
        q.delete('from_url'); q.set('returnTo', u.pathname + u.search);
        window.history.replaceState(null, '', '/login?' + q.toString());
      }
    } catch { /* ignore */ }
  }
  return <Login />;
}
import Stav from '@/pages/Stav';
import BScents from '@/pages/BScents';
import AstaIn from '@/pages/AstaIn';
import JewelryFactory from '@/pages/JewelryFactory';
import MyDeal from '@/pages/MyDeal';
import HairCosmetics from '@/pages/HairCosmetics';
import Jackson from '@/pages/Jackson';
import KelevTeva from '@/pages/KelevTeva';
import PetBest from '@/pages/PetBest';
import RedStar from '@/pages/RedStar';
import MegaPet from '@/pages/MegaPet';
import Billy from '@/pages/Billy';
import Kalahari from '@/pages/Kalahari';
import AliKarim from '@/pages/AliKarim';
import ItaiElbaz from '@/pages/ItaiElbaz';
import GaliRipui from '@/pages/GaliRipui';

// Public site: a home page (content coming) + one standalone page per client at /p/<unguessable-slug>.
// No menus, no lists: a client only ever sees their own page.
const AuthenticatedApp = () => {
  const { isLoadingAuth, isLoadingPublicSettings, authError, navigateToLogin } = useAuth();

  if (isLoadingPublicSettings || isLoadingAuth) {
    return (
      <div className="fixed inset-0 flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-stone-300 border-t-stone-800 rounded-full animate-spin"></div>
      </div>
    );
  }

  if (authError) {
    if (authError.type === 'user_not_registered') {
      return <UserNotRegisteredError />;
    } else if (authError.type === 'auth_required') {
      navigateToLogin();
      return null;
    }
  }

  return (
    <Routes>
      <Route path="/" element={<Home />} />
      {/* Eran's private index of client pages (guarded inside the page: admin only) */}
      <Route path="/admin" element={<Admin />} />
      <Route path="/crm" element={<Crm />} />
      <Route path="/login" element={<LoginRoute />} />
      <Route path="/register" element={<Register />} />
      <Route path="/forgot-password" element={<ForgotPassword />} />
      <Route path="/reset-password" element={<ResetPassword />} />
      {/* One page file + literal route per client so each shows up as its own page in the Base44 editor.
          CLIENT-ROUTES:START (generated by the IL-meta-leads pipeline) */}
      <Route path="/p/stav-56f5e275" element={<Stav />} />
      <Route path="/p/bscents-97198747" element={<BScents />} />
      <Route path="/p/astain-3f8c21d7" element={<AstaIn />} />
      <Route path="/p/jewelryfactory-8d2e61b4" element={<JewelryFactory />} />
      <Route path="/p/mydeal-5b7e19c2" element={<MyDeal />} />
      <Route path="/p/haircosmetics-8b8eb022" element={<HairCosmetics />} />
      <Route path="/p/jackson-18bceed3" element={<Jackson />} />
      <Route path="/p/kelevteva-369078b4" element={<KelevTeva />} />
      <Route path="/p/petbest-20bd483a" element={<PetBest />} />
      <Route path="/p/redstar-02f7aee4" element={<RedStar />} />
      <Route path="/p/megapet-beb32c3c" element={<MegaPet />} />
      <Route path="/p/billy-264ffd4c" element={<Billy />} />
      <Route path="/p/kalahari-7c3e91d5" element={<Kalahari />} />
      <Route path="/p/alikarim-5c8e2d71" element={<AliKarim />} />
      <Route path="/p/itai-4b1e7c93" element={<ItaiElbaz />} />
      <Route path="/p/gali-d71a3f58" element={<GaliRipui />} />
      {/* CLIENT-ROUTES:END */}
      <Route path="/p/:slug" element={<ClientPitch />} />
      <Route path="*" element={<PageNotFound />} />
    </Routes>
  );
};

function App() {
  return (
    <AuthProvider>
      <QueryClientProvider client={queryClientInstance}>
        <Router>
          <ScrollToTop />
          <AuthenticatedApp />
        </Router>
        <Toaster />
      </QueryClientProvider>
    </AuthProvider>
  )
}

export default App
