"""Export a rendered lead to the client-page template (web/base44): images + one REPORTS entry in data.js.

The page (ClientPitch.jsx) is one template for every client; everything client-specific comes from the
entry written here. `copy` holds the client-facing words (hero, review, split, band, closing, angles).
"""
from __future__ import annotations

import json
from pathlib import Path

from PIL import Image

from .common import OUTPUT, ROOT

WEB = ROOT / "web" / "base44"
DATA_JS = WEB / "src" / "reports" / "data.js"
SPEC_KEYS = ("w", "h", "direction", "box", "top", "ink", "paper", "scrim", "plate", "plate_bg", "brand_color", "obj_pos")


def _read() -> dict:
    src = DATA_JS.read_text(encoding="utf-8")
    return json.loads(src[src.index("=") + 1:].strip().rstrip(";"))


def _write(reports: dict) -> None:
    head = ("// Client report data (generated by the IL-meta-leads pipeline). Client-safe fields only.\n"
            "// One entry per client, keyed by an unguessable slug. Page: /p/<slug>\n")
    DATA_JS.write_text(head + "export const REPORTS = " + json.dumps(reports, ensure_ascii=False, indent=1) + ";\n",
                       encoding="utf-8")


def _webp(src: Path, dst: Path, max_w: int = 1400) -> None:
    im = Image.open(src).convert("RGB")
    if im.width > max_w:
        im = im.resize((max_w, round(im.height * max_w / im.width)), Image.LANCZOS)
    dst.parent.mkdir(parents=True, exist_ok=True)
    im.save(dst, "WEBP", quality=86)


def export_lead(lead: dict, slug: str, folder: str, copy: dict, hero_img: str | None = None) -> dict:
    """Write images to public/reports/<folder>/ and the REPORTS[slug] entry; returns the entry."""
    base = OUTPUT / lead["lead_id"]
    pub = WEB / "public" / "reports" / folder
    ads = []
    for ad in lead["new_ads"]:
        r = ad["layout"]["render"]
        _webp(base / ad["image_raw"], pub / f"raw_{ad['ad_no']:02d}.webp")
        spec = {k: (list(r[k]) if isinstance(r.get(k), tuple) else r.get(k)) for k in SPEC_KEYS}
        spec.update(headline=ad["overlay"], sub=ad.get("overlay_sub"), note=ad.get("note"),
                    signature=r.get("signature") or None)
        ads.append(dict(no=ad["ad_no"], angle=ad["angle_id"], format=ad["format"],
                        img=f"/reports/{folder}/raw_{ad['ad_no']:02d}.webp", headline=ad["headline"],
                        primary=ad["primary_text"], cta=ad["cta"], spec=spec))
    if hero_img:
        _webp(base / hero_img, pub / "hero.webp", max_w=1800)
    entry = dict(slug=slug, ads=ads, hero_bg=f"/reports/{folder}/hero.webp", **copy)
    reports = _read()
    reports[slug] = entry
    _write(reports)
    return entry
